attestationreport: integrated Intel SGX and TDX verifier
Fraunhofer-AISEC/cmc pull request #160
Opened 2023-12-11 16:25 UTC by CodingChrisIO

### Changes: 

- **intel_helpers.go**: 
  - common structs and parsing functions for SGX/TDX Collateral, Certificates, ...
  - helper functions for quote and collateral verification, fetching CRLs, ...
- **sgx.go** (SGX Quote Verification)
- **sgx_test.go** (Tests for the SGX verification function)
- **tdx.go** (TDX Quote Verification)
- **tdx_test.go** (Tests for the TDX verification function)
- **attestationreport_test.go** (added tests for the generic report Verify() function with TDX)
- **attestationreport.go** (added SGX/TDX specific structs)
- **verificationreport.go** (added SGX/TDX specific structs)

2024-01-09 14:21 UTC, smo4201 requested changes

2024-01-09 15:34 UTC, CodingChrisIO commented on .gitignore
> +attestationreport/cache/*
Ja, wenn man die Tests ausführt und keinen expliziten Ort für den Cache spezifiziert, werden die Zertifikate in diesem Ordner abgelegt und diese sollten nicht auf remote gepushed werden.

2024-01-09 15:37 UTC, CodingChrisIO commented on attestationreport/attestationreport.go
> +// element of types 'SNP Reference Value', 'TPM Reference Value', TDX Reference Value'
Ok und 'SGX Reference Value' muss auch noch hinzugefügt werden

2024-01-09 16:10 UTC, CodingChrisIO commented on attestationreport/attestationreport.go
> +func Verify(arRaw, nonce, casPem []byte, policies []byte, polEng PolicyEngineSelect, intelCache string) VerificationResult {
We need to tell fetchCRL where the CRL cache is. This method is defined in intel_helpers.go and is called by verifyTdxMeasurements and verifySgxMeasurements. We pass the intelCache parameter that we have from the config to the verify() method (e.g. via libapi). I think this is the best way.

2024-01-09 16:44 UTC, mokamhuber requested changes
Sieht grundsätzlich schon sehr gut aus. Ein paar Kleinigkeiten hab ich noch angemerkt :)

2024-01-09 16:44 UTC, mokamhuber commented on attestationreport/sgx.go
> +	// TODO: handle other QECertDataTypes (for now: throw an error)
hältst du es für sinnvoll/realistisch, dass wir zeitnah auch andere QECertDataTypes unterstützen?
Falls nicht, würde ich vllt. statt der etwas provokanten "TODO"-Formulierung eher sagen "Currently only ... is supported"

2024-01-09 16:44 UTC, mokamhuber commented on attestationreport/sgx.go
> +		// TODO: check how to compare CPUSVN value
können wir dieses TODO noch lösen, bevor wir den PR schließen?

2024-01-09 16:44 UTC, mokamhuber commented on attestationreport/sgx.go
> +// Copyright (c) 2021 Fraunhofer AISEC
bei neuen Dateien sollten wir vielleicht "Copyright (c) 2024" schreiben und bei den geänderten evtl. 2021-2024

2024-01-09 16:44 UTC, mokamhuber commented on attestationreport/sgx_test.go
> +			name: "Invalid Nonce",
ist das nicht der Fehlerfall "invalid MRSIGNER"?

2024-01-09 16:44 UTC, mokamhuber commented on attestationreport/sgx_test.go
> +		},
Wollen wir evtl. noch weitere Fehlerfälle für eine fehlerhafte Signatur des Measurements oder eine kaputte Zertifikatskette hinzufügen?

2024-01-09 16:44 UTC, mokamhuber commented on attestationreport/sgx_test.go
> +var (
Minor: für eine bessere Lesbarkeit der Datei könnten wir evtl. die Variablendefinitionen vergleichbar zu snp_test.go ans Ende des Files schieben, damit man beim Öffnen der Datei gleich direkt die Testfälle sieht

2024-01-09 16:44 UTC, mokamhuber commented on attestationreport/tdx.go
> +	// TODO: support other report types
Ist das zeitnah realistisch? Sonst könnten wir evtl. auch einfach nur sagen "currently we only support report type v4"

2024-01-23 16:28 UTC, smo4201 approved these changes

2024-01-23 16:33 UTC, mokamhuber approved these changes

2024-01-29 17:00 UTC, merged